name: release

on:
  push:
    branches: [main]


jobs:
  build-artifact:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Set up Docker buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Meta
      id: meta
      run: |
        echo SHORT_SHA=$(git rev-parse --short HEAD) >> $GITHUB_OUTPUT

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        platforms: |
          linux/arm64/v8
          linux/amd64
        push: true
        tags: |
          pacgi/cv:${{ steps.meta.outputs.SHORT_SHA }}
          pacgi/cv:latest

  deploy:
    needs: build-artifact
    runs-on: ubuntu-latest
    steps:
    - name: Install yq
      run: |
        echo curl -L https://github.com/mikefarah/yq/releases/download/${VERSION}/${BINARY}.tar.gz
        curl -L https://github.com/mikefarah/yq/releases/download/${VERSION}/${BINARY}.tar.gz | tar xz && sudo mv ${BINARY} /usr/bin/yq
        yq --version
      env:
        VERSION: v4.35.1
        BINARY: yq_linux_amd64

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Build Meta
      id: meta
      run: |
        echo SHORT_SHA=$(git rev-parse --short HEAD) >> $GITHUB_OUTPUT

    - name: Update deployment tag
      run: |
        yq ".spec.template.spec.containers[0].image = \"pacgi/cv:${{ steps.meta.outputs.SHORT_SHA}}\"" -i deploy/deployment.yaml

    - name: Push release
      run: |
        git config --global user.name "CI"
        git config --global user.email "ci@pacgi.dev"
        git commit -am "update deployment"
        git push
