name: release

on:
  push:
    branches: [main]


jobs:
  release-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Set up Docker buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Meta
      id: meta
      run: |
        echo SHORT_SHA=$(git rev-parse --short HEAD) >> $GITHUB_OUTPUT

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        platforms: |
          linux/arm64/v8
          linux/amd64
        push: true
        tags: |
          pacgi/cv:${{ steps.meta.outputs.SHORT_SHA }}
          pacgi/cv:latest

